###
GET http://localhost:3000/planters/test2

### Get All Planters
GET http://localhost:3000/planters

### Initialize Arduino
POST http://34.64.144.6:3000/planters
//POST http://127.0.0.1:3000/planters
content-type: application/json

{
  "planterId": "testy11111",
  "farm": "61b6fad5658cb24ac86cead7",
  "publicIP": "1.2.3.4",
  "numOfFloor": 4,
  "port": 101,
  "localIP": "2.3.4.6"
}

### Get planters current status
GET http://34.64.144.6:3000/planters/61b82803be16ca6e1b9af29e/current


### Initialize Camera
POST http://34.64.144.6:3000/planters/testy11111/cameras/sgf12-04
//POST http://127.0.0.1:3000/planters/testy11111/cameras/sgf12-04
content-type: application/json

{
  "cameraId": "sgf12-04",
  "webPort": 101,
  "streamingPort": 123,
  "publicIP": "1.2.3.4",
  "floor": 4,
  "localIP": "2.3.4.6"
}

### Initialize Camera
PATCH http://34.64.144.6:3000/planters/testy11111/cameras/sgf12-04
//PATCH http://127.0.0.1:3000/planters/testy11111/cameras/sgf12-04
content-type: application/json

{
  "plantId": "ka",
  "transferredAt": "2012-04-23T18:25:43.511Z"
}